// <auto-generated />
using System;
using Financing.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Financing.Migrations
{
    [DbContext(typeof(TransactionContext))]
    [Migration("20181129103436_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Financing.Models.Transaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<int>("Price");

                    b.Property<string>("Status");

                    b.Property<DateTime>("TargetMonth");

                    b.Property<string>("Title");

                    b.Property<string>("Type");

                    b.HasKey("ID");

                    b.ToTable("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
